#### Q1. Write a Python program to get the string from the given string where all the occurrence of its first char has been changed to $,' except first char itself?
 
Sample String: 'prospect'<br/>
Expected Result : 'pros$ect'

In [1]:
input_string = input("Enter string:")

l=[]
op_string = ''
for s in input_string:
    if(s in l):
        op_string +="$"
    else:
        op_string +=s
    
    l.append(s)
    
op_string

Enter string:prospect


'pros$ect'

#### Q2. Write a Python program to get the single string from the two given strings, and separated by the space and swap the first two characters of  each string?

Sample String : 'abc', 'xyz'. <br/>
Expected Result: 'xyc abz'

In [2]:
string1 = 'abc'
string2 = 'xyz'

op_string1 = string2[:2]+string1[2:]
op_string2 = string1[:2]+string2[2:]
op_string =  op_string1 + " " +  op_string2

op_string

'xyc abz'

##### Q3. Write the Python program to add 'ing' at the end of the given string (length of the string should be at least 3). If given string already ends with 'ing,' then add 'ly' instead. If string length of the given string is less than 3, leave it unchanged?

 Sample string: ' abc ' <br/>
 Expectedresult: 'abcing' <br/>
 Samplestring: 'string' <br/>
 Expectedresult: 'stringly'<br/>

In [3]:
s= "abc"

if(len(s) >= 3):
    if(s[-3:] != 'ing'):
        s +="ing"
    else:
        s +="ly"

s

'abcing'

##### Q4. Write the Python program to find the first appearance of the substring 'not' and 'poor' from the given string, if 'not' follows the 'poor', replace the whole 'not'...' poor' substring with 'good'.Return the resulting string.

 Sample string: 'The lyrics are not that poor!'
 'The lyrics are poor!' <br/>
 Expected Result: 'The lyrics are good!'
 'The lyrics are poor!'

In [4]:
def poor_good(s):
    s_not = s.find("not")
    s_poor = s.find("poor")
    
    if ( ( s_not >0 and s_poor > 0 ) and s_not < s_poor ):
        op_string = s.replace(s[s_not:(s_poor+4)],"good")
    else:
        op_string = s
    
    return op_string

op_string = poor_good('The lyrics are not that poor!')

print(op_string)

The lyrics are good!


#### Q5. Write the Python program to remove the characters which have odd index values of a given string.

In [5]:
s = "0123456789"

s[0::2] #print even string

'02468'

#### Q6. Write the Python function to get a string made of 4 copies of the last two characters of the specified string (length must be at least 2).

In [6]:
def insert_end(string):
    if(len(string)>2):
        return string[-2:] * 4

insert_end("Python")

'onononon'

#### Q7. Write the python function to get a string made of its first three characters of a specified string. If then return the original string.

Sample function and result : <br/>
 first-three('ipy') -> ipy <br/>
 first-three('python') -> pyt

In [7]:
def first_three(s):
    if(len(s) > 3):
        return s[:3]
    else:
        return s

op_string = first_three("python")
op_string1 = first_three("ipy")

print(op_string)
print(op_string1)

pyt
ipy


##### Q8. Write the python program to print the following floating numbers up to 2 decimal places?


In [8]:
number = 12.38989

print("Number upto 2 Decimals: {:.2f}".format(number))

Number upto 2 Decimals: 12.39


#### Q9. Write the Python program to format a number with a percentage?

In [9]:
number = 0.25

print("Percentage: {:.2%}".format(number))

Percentage: 25.00%


#### Q10. Write the Python program to count occurrences of a substring in a String?

In [10]:
input = "man"
string = "dhmandhman"

string.count(input)

2

#### Q11. Write the Python program to count repeated characters in a string.

In [11]:
string = "thequickbrownfoxjumpsoverthelazydog"
l=[]
for s in string:
    if(string.count(s) > 1 and s not in l):
        l.append(s)
        print("%s: %d"%(s,string.count(s)))

t: 2
h: 2
e: 3
u: 2
r: 2
o: 4


#### Q12. Write the Python program to print the square and cube symbol in the area of a rectangle and volume of a cylinder?

In [12]:
area_rectangle = 1256.66
vol_cylinder = 1254.725

print("The area of the rectangle is {:.2f}cm\u00b2".format(area_rectangle))
print("The volume of the cylinder is {:.2f}cm\u00b3".format(vol_cylinder))

The area of the rectangle is 1256.66cm²
The volume of the cylinder is 1254.72cm³


#### Q13 Write the Python program to check if a string contains all letters of the alphabet?

In [13]:
input_string = "the quick brown fox jumps over the lazy cat"

alpha = 'a'
missing = 0
for i in range(0, 26): 
    if(alpha not in input_string):
        missing = 1
        print("{} is missing".format(alpha))
    alpha = chr(ord(alpha) + 1) 

if(missing == 0):
    print("No alphabet is missing")

d is missing
g is missing


#### Q14. Write the Python program to find the second most repeated word in a given string?

In [14]:
def findSecondRepeatedWord(input_string):
    words = input_string.split(" ")
    
    word_count = {}
    for word in words:
        word_count[word]=words.count(word)
    
    sorted_word = sorted(word_count.values(),reverse=True)
    secondLarge = sorted_word[1] 
    
    for (key,val) in word_count.items():
        if val == secondLarge:
            print("2nd Most repeated word in string is {} with count {}".format(key,val))

input_string = "hello world world how how how "
findSecondRepeatedWord(input_string)

2nd Most repeated word in string is world with count 2


##### Q.15 Write the Python program to find the minimum window in the given string, which will contains all the characters of another given strings

In [15]:
# containing all characters of a pattern.  
no_of_chars = 256
  
# Function to find smallest window  
# containing all characters of 'pat'  
def findSubString(string, pat):  
  
    len1 = len(string)  
    len2 = len(pat)  
  
    # check if string's length is less than pattern's  
    # length. If yes then no such window can exist  
    if len1 < len2:  
      
        print("No such window exists")  
        return ""  
  
    hash_pat = [0] * no_of_chars 
    hash_str = [0] * no_of_chars  
  
    # store occurrence ofs characters of pattern  
    for i in range(0, len2):  
        hash_pat[ord(pat[i])] += 1
  
    start, start_index, min_len = 0, -1, float('inf')  
  
    # start traversing the string  
    count = 0 # count of characters  
    for j in range(0, len1):  
      
        # count occurrence of characters of string  
        hash_str[ord(string[j])] += 1
  
        # If string's char matches with  
        # pattern's char then increment count  
        if (hash_pat[ord(string[j])] != 0 and hash_str[ord(string[j])] <= hash_pat[ord(string[j])]):  
            count += 1
  
        # if all the characters are matched  
        if count == len2:  
          
            # Try to minimize the window i.e., check if  
            # any character is occurring more no. of times  
            # than its occurrence in pattern, if yes  
            # then remove it from starting and also remove  
            # the useless characters.  
            while (hash_str[ord(string[start])] >  hash_pat[ord(string[start])] or hash_pat[ord(string[start])] == 0):  

                if (hash_str[ord(string[start])] >  hash_pat[ord(string[start])]):  
                    hash_str[ord(string[start])] -= 1
                
                start += 1
              
            # update window size  
            len_window = j - start + 1
            if min_len > len_window:
                min_len = len_window  
                start_index = start  
  
    # If no window found  
    if start_index == -1: 
        print("No such window exists")  
        return ""  
      
    # Return substring starting from  
    # start_index and length min_len  
    return string[start_index : start_index + min_len]  


string = "PRWSOERIUSFK"
pattern = "OSU"

findSubString(string,pattern)

'SOERIU'

#### Q17. Write the Python program to count number of substrings from a given string of lowercase alphabets with exactly k distinct (given) characters?

In [2]:
def findSubString(string,k):
    count = 0
    for s in string.split(" "):
        if(len(s) == k): 
            count += 1
    return count


str1 = input("Input a string lowercase alphabet:")
k = int(input("Input k: "))

sub_str_count = findSubString(str1,k)

print("Number of substrings with exactly {} distinct characters: {}".format(k,sub_str_count))

Input a string lowercase alphabet:wolf
Input k: 4
Number of substrings with exactly 4 distinct characters: 1


#### Q18  Write the Python program to count number of non-empty substrings of the given string?

In [3]:
def findSubStr(strinng):
    sub_str= "";
    str_length = len(string)+1
    count = 0
    
    for i in range(0,str_length):
        for j in range(i+1,str_length):
                sub_str += string[i:j] + ", "
                count +=1
    
    return sub_str,count

string = input("Enter string: ")
sub_str,count = findSubStr(string)
print("Substring Occurances: {}".format(sub_str[:-1]))
print("Count = {}".format(count))

Enter string: w3resource
Substring Occurances: w, w3, w3r, w3re, w3res, w3reso, w3resou, w3resour, w3resourc, w3resource, 3, 3r, 3re, 3res, 3reso, 3resou, 3resour, 3resourc, 3resource, r, re, res, reso, resou, resour, resourc, resource, e, es, eso, esou, esour, esourc, esource, s, so, sou, sour, sourc, source, o, ou, our, ourc, ource, u, ur, urc, urce, r, rc, rce, c, ce, e,
Count = 55


#### Q19. Write the Python program to count number of substrings with same first and last characters of the given string?

In [4]:
def findSubStrWithEqualEnd(string):
    sub_str= "";
    str_length = len(string)+1
    count = 0
    
    for i in range(0,str_length):
        for j in range(i+1,str_length):
            if( len(string[i:j])  == 1) or ( len(string[i:j])  > 1  and ( string[i] == string[j-1] )):
                sub_str += string[i:j] + ", "
                count +=1
    
    return sub_str,count

string = input("Enter string: ")
sub_str,count = findSubStrWithEqualEnd(string)
print("Substring with Same first and last characters: {}".format(sub_str[:-1]))
print("Count = {}".format(count))

Enter string: abcab
Substring with Same first and last characters: a, abca, b, bcab, c, a, b,
Count = 7


#### Q20. Write the Python program to count the number of strings where the string length is 2 or more, and first and last character are same from a given list of strings.

In [19]:
def findSubStrWithEqualEnd(str_list):
    count = 0
    for s in str_list:
        if(s[0] == s[-1] and len(s) > 2):
            count+=1;
    
    return count

str_list=['abc','xyz','wxyw','121231','11']
findSubStrWithEqualEnd(str_list)

2

#### Q21 Write the Python program to get a list, sorted in increasing order by the last element in each tuple from the given list of non-empty tuples?

In [1]:
def getSortedTuple(tuple_list):
    tuple_list.sort(key = lambda x:x[1])
    return tuple_list

tuple_list=[(2,5),(1,2),(4,4),(2,3),(2,1)]
getSortedTuple(tuple_list)

[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]

#### Q22. Write the Python program to remove duplicates from a list?

In [35]:
listOfStudents = ["John","Alice","Zec","Dan","John"]
list(set(listOfStudents))


['Alice', 'John', 'Zec', 'Dan']

#### Q23. Write the Python program to find the list of words that are longer than n from a given list of words?


In [34]:
listOfStudents = ["John","Alice","Zec","Dan","John"]
n=4
[student for student in listOfStudents if len(student)> n]

['Alice']

#### Q24. Write the Python program to print a specified list after removing the 0th, 4th, and 5th elements?

In [19]:
list_color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
new_list = [ value for index,value in enumerate(list_color) if index not in (0,4,5)]
new_list

['Green', 'White', 'Black']

#### Q25. Write the Python program to generate all permutations of a list in Python?

In [44]:
from itertools import permutations 
perm = permutations(['a', 'b','c' ], 2) 
list(perm)

[('a', 'b'), ('a', 'c'), ('b', 'a'), ('b', 'c'), ('c', 'a'), ('c', 'b')]

#### Q26: Write the Python program to convert a pair of values into a sorted unique array?

In [36]:
input = [ (1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10) ]

new_list = set()
for key,value in input:
    new_list.add(key)
    new_list.add(value)

list(sorted(new_list))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Q27. Write the Python class to convert an integer to a roman numeral?

In [21]:
class IntRomanConverter:

    romanTbl = {1: "I", 4: "IV", 5: "V", 9: "IX", 10: "X", 40: "XL", 50: "L", 90: "XC", 100: "C",
                400: "CD", 500: "D", 900: "CM", 1000: "M"}

    def find_minimal_decimal(self, num):
        nearest_decimal = []
        for i in self.romanTbl.keys():
            if i <= num:
                nearest_decimal.append(i)
            elif i > num:
                break
        return nearest_decimal[-1]

    def int_to_roman(self, num, roman_num=""):
        nearest_decimal = self.find_minimal_decimal(num)
        remaining_num = num - nearest_decimal

        if num == nearest_decimal:
            roman_num += self.romanTbl[nearest_decimal]
            return  roman_num
        elif num > nearest_decimal:
            roman_num += self.romanTbl[nearest_decimal]
            return self.int_to_roman(remaining_num, roman_num)


int_romn_convt = IntRomanConverter()

roman_number = int_romn_convt.int_to_roman(22)

print(roman_number)

XXII


#### Q28 Write the Python class to convert a Roman numeral to an integer?

In [22]:
class RomanIntConverter:

    romanTbl = {"I":1,"IV":4,"V":5,"IX":9,"X":10,"XL":40,"L":50,"XC":90,"C":100,"CD":400,"D":500,"CM":900,"M":1000}


    def roman_to_int(self, roman_val):
        try:
            if len(roman_val) == 1:
                return self.romanTbl[roman_val]
                    
            i=0
            total = 0
            for roman_sym in roman_val:
                if self.romanTbl[roman_val[i]] >= self.romanTbl[roman_val[i+1]]:
                    total += self.romanTbl[roman_sym]
                else:
                    total -= self.romanTbl[roman_sym]
            i+=1
            return total;
        except:
            print("Symbol not present")
            return ""
            


romn_int_convt = RomanIntConverter()

int_number = romn_int_convt.roman_to_int("XXII")

print(int_number)

22


#### Q29: Write the Python class to find the validity of the string of the parentheses, '(', ')', '{', '}', '[' and '] and the brackets must be closed in the correct order, example - "()" and "()[]{}" are valid but "[)", "({[)]" and "{{{" are invalid.

In [37]:
class ValidateBrackets:
    
    def validate_brackets(self,brackets):
        bracket_list,bracket_char = [],{"(":")","{":"}","[":"]"}
        
        for bracket in brackets:
            if bracket in bracket_char:
                bracket_list.append(bracket)
            elif len(bracket_list) == 0 or bracket != bracket_char[bracket_list.pop()]:
                return False
        return len(bracket_list) == 0

brackets = ValidateBrackets()
print( brackets.validate_brackets("{}[]{()]") )
print( brackets.validate_brackets("()[]{}") )
print( brackets.validate_brackets("{}[]{}]") )

False
True
False


#### Q30. Write the Python class to get all possible unique subsets from a set of distinct integers?

In [261]:
class SubSets:
    def subSet(self,input_list):
        new_list = [[]]
        for i in range(0,len(input_list)):
            new_list.append([input_list[i]])
            for j in range(0,i):
                new_list.append(input_list[j:i+1])

        return new_list
                
sub_set = SubSets()
op = sub_set.subSet([4,5,6])
print(op)

[[], [4], [5], [4, 5], [6], [4, 5, 6], [5, 6]]


#### Q31. Write the Python class to find a pair of elements (indices of the two numbers) from a given array whose sum equals the specific target number?

In [310]:
class findPair:
    def find_pair_element(self,start_index,input_list,target):
        cur = input_list[start_index]
        for i in range(start_index,len(input_list)):
            if cur + input_list[i] == target:
                return [input_list.index(cur),input_list.index(input_list[i])]
        else:
            start_index +=1
            return self.find_pair_element(start_index,input_list,target)
        
fp = findPair()

input_list=[10,20,10,40,50,60,70]
target = 90
start_index = 0

op = fp.find_pair_element(start_index,input_list,target)
print(op)

[1, 6]


#### Q32. Write the Python class to find the three elements that sum to zero from the set of n real numbers?

In [1]:
class SumToZero:
    def find_pair_element(self,n,arr): 
        found = False
        result = []
        # sort array elements 
        arr.sort() 

        for i in range(0, n-1): 

            # initialize left and right 
            l = i + 1
            r = n - 1
            x = arr[i] 
            while (l < r): 

                if (x + arr[l] + arr[r] == 0): 
                    # print elements if it's sum is zero 
                    result.append([x, arr[l], arr[r]]) 
                    l+=1
                    r-=1


                # If sum of three elements is less 
                # than zero then increment in left 
                elif (x + arr[l] + arr[r] < 0): 
                    l+=1

                # if sum is greater than zero than 
                # decrement in right side 
                else: 
                    r-=1
        return result
        
obj = SumToZero()

input_list=[-25,-10,-7, -3, 2, 4, 8, 10]

op = obj.find_pair_element(len(input_list),input_list)
print(op)

[[-10, 2, 8], [-7, -3, 10]]


#### Q48: Write the NumPy program to create a 2d array with 6 on the border and 0 inside?

In [10]:
import numpy as np
x = 5 + np.ones((5,5))
x[1:4,1:4] = 0
x

array([[6., 6., 6., 6., 6.],
       [6., 0., 0., 0., 6.],
       [6., 0., 0., 0., 6.],
       [6., 0., 0., 0., 6.],
       [6., 6., 6., 6., 6.]])

#### Q49. Write the NumPy program to create a 8x8 matrix and fill it with the checkerboard pattern?

In [43]:
x = 2 + np.ones((8,8),dtype=int)

x[1::2,::2] = 9
x[::2,1::2] = 9
x

array([[3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3]])

#### Q50. Write the NumPy program to create an empty and a full array.

In [83]:
x = np.empty((3,4))
y = np.full((3,3),6)

print(x,y,sep="\n\n")

[[0.e+000 0.e+000 8.e-323 0.e+000]
 [0.e+000 0.e+000 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000 0.e+000]]

[[6 6 6]
 [6 6 6]
 [6 6 6]]


#### Q51. Write the NumPy program to convert the values of Centigrade degrees into the Fahrenheit degrees and the centigrade values are stored in the NumPy array.

In [114]:
temp_f = np.array([0, 12, 45.21 ,34, 99.91],dtype=float)
temp_c = (temp_f - 32) * 5/9
temp_c

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])

#### Q52. Write the NumPy program to find the real and imaginary parts of an array of complex numbers?

In [127]:
x = np.array([1+2j, 3+4j, 5+6j])
x = np.array([ 1.00000000+0.j,0.70710678+0.70710678j])
print("Real Part",x.real)
print("Imagniary Part",x.imag)

Real Part [1.         0.70710678]
Imagniary Part [0.         0.70710678]


#### Q53. Write the NumPy program to test whether each element of a 1-D array is also present in the second array?

In [133]:
x = np.array([0,10,20,40,60])
y = np.array([0,40])

np.isin(x,y)

array([ True, False, False,  True, False])

### Q54. Write the NumPy program to find common values between two arrays?

In [135]:
x = np.array([0,10,20,40,60])
y = np.array([10,30,40])

np.intersect1d(x,y)

array([10, 40])

#### Q55. Write the NumPy program to get the unique elements of an array?

In [149]:
x = np.array([10,10,20,20,30,30])
print(np.unique(x))

y = np.array([[1,1],[2,3]])

np.unique(y)

[10 20 30]


array([1, 2, 3])

#### Q56. Write the NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays?

In [154]:
array1 = np.array([0,10,20,40,60,80])
array2 = np.array([10, 30, 40, 50, 70])
np.setxor1d(array1,array2)

array([ 0, 20, 30, 50, 60, 70, 80])

#### Q57. Write the NumPy program to test if all elements in an array evaluate to True ?

In [164]:
x = np.array([10,20,40,60,80])
print(np.all(x))

y = np.array([[True,True],[False,False]])
print(np.all(y))

y = np.array([[True,True],[True,True]])
print(np.all(y))

True
False
True


#### Q59. Write the NumPy program to construct an array by repeating?

In [185]:
x = np.array([1,2,3,4])
print("Repating 2 times: ", np.tile(x,2) )
print("Repating 3 times: ",np.tile(x,3))

Repating 2 times:  [1 2 3 4 1 2 3 4]
Repating 3 times:  [1 2 3 4 1 2 3 4 1 2 3 4]


#### Q60. Write the NumPy program to find the indices of the maximum and minimum values with the given axis of an array?

In [192]:
x = np.array([1,2,3,4,5,6])

print("Min: ", np.argmin(x) )
print("Max: ",np.argmax(x) )

Min:  0
Max:  5


#### Q61. Write the NumPy program compare two arrays using numpy?

In [202]:
x = np.array([1,2])
y = np.array([2,4])

print("x > y ",np.greater(x,y))
print("x >= y ",np.greater_equal(x,y))
print("x < y ",np.less(x,y))
print("x <= y ",np.less_equal(x,y))

x > y  [False False]
x >= y  [False False]
x < y  [ True  True]
x <= y  [ True  True]


#### Q62. Write the NumPy program to sort an along the first, last axis of an array?

In [221]:
x = np.array([[4,6],[2,1]])

np.sort(x,axis=0)

array([[2, 1],
       [4, 6]])

#### Q63. Write the NumPy program to sort pairs of first name and last name return their indices (first by last name, then by first name).

In [235]:
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')
x = np.lexsort((first_names, last_names))
x

array([0, 1, 2, 3, 4])

#### Q64. Write the NumPy program to get the values and indices of the elements that are bigger than 10 in the given array?

In [233]:
x = np.array([[10,20,30],[20,30,40]])
print("Values > 10 ",x[x>10])
print("Indices",np.nonzero(x > 10))

Values > 10  [20 30 20 30 40]
Indices (array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))


#### Q65. Write the NumPy program to find the memory size of a NumPy array?

In [239]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


#### Q66. Write the NumPy program to create an array of ones and an array of zeros?

In [247]:
print("Create an array of zeros")
x = np.zeros((1,2))
print("Default type is float")
print(x)
print("Type changes to int")
x = np.zeros((1,2), dtype = np.int)
print(x)
print("Create an array of ones")
y= np.ones((1,2)) 
print("Default type is float")
print(y)
print("Type changes to int")
y = np.ones((1,2), dtype = np.int)
print(y)

Create an array of zeros
Default type is float
[[0. 0.]]
Type changes to int
[[0 0]]
Create an array of ones
Default type is float
[[1. 1.]]
Type changes to int
[[1 1]]


#### Q67. Write the NumPy program to change the dimension of an array?

In [266]:
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and columns")
print(x.shape)
print("\n")
y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)
print("\n")
y = np.array([1, 2, 3, 4, 5, 6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
y.shape = (3,3)

6 rows and columns
(6,)


(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Change array shape to (3, 3) -> 3 rows and 3 columns 


#### Q68. Write the NumPy program to create a new shape to an array without changing its data ?

In [273]:
x = np.array([1,2,3,4,5,6])

x.shape = (3,2)
print("Reshape 3x2 - ",x,sep="\n")

x.shape = (2,3)
print("Reshape 2x3 - ",x,sep="\n")

Reshape 3x2 - 
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3 - 
[[1 2 3]
 [4 5 6]]


#### Q69. Write the NumPy program to create a new array of 3*5, filled with 2?

In [280]:
x = 1 + np.ones((3,5))

x

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

#### Q70. Write the NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere?

In [293]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q71. Write the NumPy program to split an array of 14 elements into the 3 arrays and each of which has 2, 4, and 8 elements in original order?

In [312]:
x = np.arange(1,15)

np.split(x,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

#### Q72. Write the NumPy program to split of an array of shape 4x4 it into two arrays along the second axis ?

In [333]:
x = np.arange(16).reshape(4,4)
x1 = x[:,:2]
x2 = x[:,2:]

print(x)
print(np.hsplit(x,[2,6]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]


#### Q73. Write the NumPy program to create a 5x5 matrix with row values ranging from 0 to 4?

In [348]:
x = np.zeros((5,5)) + np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### Q74. Write the NumPy program to create an array of zeros and three column types (integer, float, character)?

In [357]:
x = np.zeros((3,), dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data
x

array([(1, 2., b'Albert Einstein'), (2, 2., b'Edmond Halley'),
       (3, 3., b'Gertrude B. Elion')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S40')])

#### Q75. Write the NumPy program to remove the negative values in the numpy array with 0?

In [361]:
x = np.array([-1,-4,0,2,3,4,5,-6])
x[x<0] = 0
x

array([0, 0, 0, 2, 3, 4, 5, 0])

#### Q101. Write the Python program to add, subtract, multiply and divide two pandas series ?

In [7]:
import pandas as pd

labels = ['a','b','c','d','e']

s1 = [2, 4, 6, 8, 10]
s2 = [1, 3, 5, 7, 9]

pd_seris1 = pd.Series(s1)
pd_seris2 = pd.Series(s2)

print("Add : ", pd_seris1 + pd_seris2 )
print("Sub : ", pd_seris1 - pd_seris2 )
print("Multiply:",pd_seris1 * pd_seris2 )
print("Divide:",pd_seris1 / pd_seris2 )

Add :  0     3
1     7
2    11
3    15
4    19
dtype: int64
Sub :  0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply: 0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide: 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#### Q102. Write a Python program to convert a dictionary to the Pandas Series?

In [24]:
d = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
pd.Series(d)

a    100
b    200
c    300
d    400
e    800
dtype: int64

#### Q103. Write a python program to change the data type of given a column or a Series?

In [49]:
s1=[100,200,"python",300.12,400]

df = pd.DataFrame(s1,columns=["foo"])
df

foo
0     100
1     200
2  python
3  300.12
4     400

In [53]:
df['foo'] = pd.to_numeric(df['foo'], errors='coerce')

df['foo']

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
Name: foo, dtype: float64

#### Q104. Write the python pandas program to convert the first column of a DataFrame as a Series?

In [63]:
r1 = [0,1,4,7]
r2 = [1,2,5,5]
r3 = [2,3,6,8]
r4 = [3,4,9,12]
r5 = [4,7,5,1]
r6 = [5,11,0,11]

my_data = {'c1':[0,1,2,3,4,5],
           'c2':[1,2,3,4,7,11],
           'c4':[4,5,6,9,5,0],
           'c3':[7,5,8,12,1,11],
          }

df = pd.DataFrame(my_data)

s1 = df['c2']
print(s1)
type(s1)

0     1
1     2
2     3
3     4
4     7
5    11
Name: c2, dtype: int64


pandas.core.series.Series